#!/usr/bin/bash
SCRIPT_DIR=$(dirname $0)
WITH_LEAK_CHECK=0

if [ $# -lt 1 ]; then
    echo "Usage: $0 <source>"
    exit 1
fi

BIN_DIR="${SCRIPT_DIR}/bin"
if [ ! -d $BIN_DIR ];
then
    echo "Creating the bin directory"
    mkdir -p $BIN_DIR
fi

SOURCE=$1
TARGET=$(basename $SOURCE)
TARGET="${SCRIPT_DIR}/bin/${TARGET%.*}.asm"

echo "Manufacturing the HELLIUM Compiler"
make -f MAKEFILE
STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "Failed to manufacture the HELLIUM Compiler"
    exit $STATUS
fi

echo "Compiling $SOURCE into $TARGET"

if [ $WITH_LEAK_CHECK -eq 1 ]; then
    valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes $SCRIPT_DIR/bin/heliumc $SOURCE $TARGET
else
    $SCRIPT_DIR/bin/heliumc $SOURCE $TARGET
fi

STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "Failed to compile $SOURCE"
    exit $STATUS
fi

OUTPUT="${TARGET%.*}.o"
nasm  -f elf64 -o $OUTPUT $TARGET
STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "Failed to assemble $TARGET"
    exit $STATUS
fi

EXECUTABLE="${TARGET%.*}"
gcc  -no-pie $OUTPUT -o "${EXECUTABLE}" 
STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "Failed to link $OUTPUT"
    exit $STATUS
fi

$EXECUTABLE
STATUS=$?
echo "Execution status: $STATUS"